export const USER_DATA_FETCH_INIT = 'USER_DATA_FETCH_INIT';
export const USER_DATA_FETCH_SUCCESS = 'USER_DATA_FETCH_SUCCESS';
export const USER_DATA_FETCH_ERROR = 'USER_DATA_FETCH_ERROR';

export const SET_UI_DATA = 'SET_UI_DATA';
